# Working With Pandas Data Frames
---

* Import the pandas library as pd and read in the csv that we just wrote as a data frame using the `read_csv`.

In [3]:
import pandas as pd
df = pd.read_csv('../data/gapminder_final.csv')

* return the data frame from jupyter to view it (pretty)

In [4]:
df

          country  year         pop continent  lifeExp    gdpPercap
0     Afghanistan  1997  22227415.0      Asia   41.763   635.341351
1     Afghanistan  2002  25268405.0      Asia   42.129   726.734055
2     Afghanistan  2007  31889923.0      Asia   43.828   974.580338
3     Afghanistan  1952   8425333.0      Asia   28.801   779.445314
4     Afghanistan  1957   9240934.0      Asia   30.332   820.853030
5     Afghanistan  1962  10267083.0      Asia   31.997   853.100710
6     Afghanistan  1967  11537966.0      Asia   34.020   836.197138
7     Afghanistan  1972  13079460.0      Asia   36.088   739.981106
8     Afghanistan  1977  14880372.0      Asia   38.438   786.113360
9     Afghanistan  1982  12881816.0      Asia   39.854   978.011439
10    Afghanistan  1987  13867957.0      Asia   40.822   852.395945
11    Afghanistan  1992  16317921.0      Asia   41.674   649.341395
12        Albania  1952   1282697.0    Europe   55.230  1601.056136
13        Albania  1957   1476505.0    Europe   59.280  1942.284244
14        Albania  1962   1728137.0    Europe   64.820  2312.888958
15        Albania  1967   1984060.0    Europe   66.220  2760.196931
16        Albania  1972   2263554.0    Europe   67.690  3313.422188
17        Albania  1977   2509048.0    Europe   68.930  3533.003910
18        Albania  1982   2780097.0    Europe   70.420  3630.880722
19        Albania  1987   3075321.0    Europe   72.000  3738.932735
20        Albania  1992   3326498.0    Europe   71.581  2497.437901
21        Albania  1997   3428038.0    Europe   72.950  3193.054604
22        Albania  2002   3508512.0    Europe   75.651  4604.211737
23        Albania  2007   3600523.0    Europe   76.423  5937.029526
24        Algeria  1962  11000948.0    Africa   48.303  2550.816880
25        Algeria  1967  12760499.0    Africa   51.407  3246.991771
26        Algeria  1972  14760787.0    Africa   54.518  4182.663766
27        Algeria  1977  17152804.0    Africa   58.014  4910.416756
28        Algeria  1982  20033753.0    Africa   61.368  5745.160213
29        Algeria  1952   9279525.0    Africa   43.077  2449.008185
...           ...   ...         ...       ...      ...          ...
1674  Yemen, Rep.  1982   9657618.0      Asia   49.113  1977.557010
1675  Yemen, Rep.  1987  11219340.0      Asia   52.922  1971.741538
1676  Yemen, Rep.  1992  13367997.0      Asia   55.599  1879.496673
1677  Yemen, Rep.  1997  15826497.0      Asia   58.020  2117.484526
1678  Yemen, Rep.  2002  18701257.0      Asia   60.308  2234.820827
1679  Yemen, Rep.  2007  22211743.0      Asia   62.698  2280.769906
1680       Zambia  1952   2672000.0    Africa   42.038  1147.388831
1681       Zambia  1957   3016000.0    Africa   44.077  1311.956766
1682       Zambia  1962   3421000.0    Africa   46.023  1452.725766
1683       Zambia  1967   3900000.0    Africa   47.768  1777.077318
1684       Zambia  1972   4506497.0    Africa   50.107  1773.498265
1685       Zambia  1977   5216550.0    Africa   51.386  1588.688299
1686       Zambia  1982   6100407.0    Africa   51.821  1408.678565
1687       Zambia  1987   7272406.0    Africa   50.821  1213.315116
1688       Zambia  1992   8381163.0    Africa   46.100  1210.884633
1689       Zambia  1997   9417789.0    Africa   40.238  1071.353818
1690       Zambia  2002  10595811.0    Africa   39.193  1071.613938
1691       Zambia  2007  11746035.0    Africa   42.384  1271.211593
1692     Zimbabwe  1952   3080907.0    Africa   48.451   406.884115
1693     Zimbabwe  1957   3646340.0    Africa   50.469   518.764268
1694     Zimbabwe  1962   4277736.0    Africa   52.358   527.272182
1695     Zimbabwe  1967   4995432.0    Africa   53.995   569.795071
1696     Zimbabwe  1972   5861135.0    Africa   55.635   799.362176
1697     Zimbabwe  1977   6642107.0    Africa   57.674   685.587682
1698     Zimbabwe  1982   7636524.0    Africa   60.363   788.855041
1699     Zimbabwe  1987   9216418.0    Africa   62.351   706.157306
1700     Zimbabwe  1992  10704340.0    Africa   60.377   693.420786
1701     Zimbabwe  1997  11404948.0    Africa   46.809   792.449960
1702     Zimbabwe  2002  11926563.0    Africa   39.989   672.038623
1703     Zimbabwe  2007  12311143.0    Africa   43.487   469.709298

[1704 rows x 6 columns]

* What if we wanted to break up all the data into files for each continent?
* What if we wanted to have only one row for each country?
  * We would have to have columns for each year
  
** Don't worry about all of the code in the block below. By the end of this section it will make sense. **

In [5]:
allcountries_df = pd.read_csv("../data/gapminder_final.csv")
df_t = allcountries_df

years = sorted(list(df_t['year'].unique()))
# Convert years to strings

for year in years:
    col_name = "gdpPercap_" + str(year)
    df_t[col_name] = 0

for y in years:
    df_t.loc[df_t.year == y, "gdpPercap_" + str(y)] = df_t["gdpPercap"]

df_t = df_t.groupby(df_t["country"]).max()
df_t["pop2007"] = df_t["pop"]
df_t["lifeExp2007"] = df_t["lifeExp"]

df_t.drop("country", axis=1, inplace=True)
df_t.drop("gdpPercap", axis=1, inplace=True)
df_t.drop("year", axis=1, inplace=True)
df_t.drop("lifeExp", axis=1, inplace=True)

continents = df_t["continent"].unique()

df_t.to_csv("../data/gapminder_All.csv")

for continent in continents:
    new_df = df_t.loc[df_t["continent"] == continent]
    newfilename = "gapminder_" + continent + ".csv"
    new_df.to_csv("../data/" + newfilename)

* Check out our data folder after we ran this script. We now have six additional csv files.
    ~~~
    * gapminder_All.csv
    * gapminder_Oceana.csv
    * gapminder_Europe.csv
    * gapminder_Asia.csv
    * gapminder_Americas.csv
    * gapminder_Africa.csv
    ~~~

Lets read in the Africa csv to see how the structure has changed.

In [7]:
# Read in gapminder_Africa.csv as a data frame
df_africa = pd.read_csv("../data/gapminder_Africa.csv", index_col="country")

We can see that now there is only one row for each country. Lets re-read the file using the index_col parameter

In [8]:
# Re-read the file using index_cols
df_africa

,pop,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007,pop2007,lifeExp2007
country,,,,,,,,,,,,,,,,
Algeria,33333216.0,Africa,2449.008185,3013.976023,2550.816880,3246.991771,4182.663766,4910.416756,5745.160213,5681.358539,5023.216647,4797.295051,5288.040382,6223.367465,33333216.0,72.301
Angola,12420476.0,Africa,3520.610273,3827.940465,4269.276742,5522.776375,5473.288005,3008.647355,2756.953672,2430.208311,2627.845685,2277.140884,2773.287312,4797.231267,12420476.0,42.731
Benin,8078314.0,Africa,1062.752200,959.601080,949.499064,1035.831411,1085.796879,1029.161251,1277.897616,1225.856010,1191.207681,1232.975292,1372.877931,1441.284873,8078314.0,56.728
Botswana,1639131.0,Africa,851.241141,918.232535,983.653976,1214.709294,2263.611114,3214.857818,4551.142150,6205.883850,7954.111645,8647.142313,11003.605080,12569.851770,1639131.0,63.622
Burkina Faso,14326203.0,Africa,543.255241,617.183465,722.512021,794.826560,854.735976,743.387037,807.198586,912.063142,931.752773,946.294962,1037.645221,1217.032994,14326203.0,52.295
Burundi,8390505.0,Africa,339.296459,379.564628,355.203227,412.977514,464.099504,556.103265,559.603231,621.818819,631.699878,463.115148,446.403513,430.070692,8390505.0,49.580
Cameroon,17696293.0,Africa,1172.667655,1313.048099,1399.607441,1508.453148,1684.146528,1783.432873,2367.983282,2602.664206,1793.163278,1694.337469,1934.011449,2042.095240,17696293.0,54.985
Central African Republic,4369038.0,Africa,1071.310713,1190.844328,1193.068753,1136.056615,1070.013275,1109.374338,956.752991,844.876350,747.905525,740.506332,738.690607,706.016537,4369038.0,50.485
Chad,10238807.0,Africa,1178.665927,1308.495577,1389.817618,1196.810565,1104.103987,1133.984950,797.908101,952.386129,1058.064300,1004.961353,1156.181860,1704.063724,10238807.0,51.724
Comoros,710960.0,Africa,1102.990936,1211.148548,1406.648278,1876.029643,1937.577675,1172.603047,1267.100083,1315.980812,1246.907370,1173.618235,1075.811558,986.147879,710960.0,65.152
"Congo, Dem. Rep.",64606759.0,Africa,780.542326,905.860230,896.314634,861.593242,904.896069,795.757282,673.747818,672.774812,457.719181,312.188423,241.165877,277.551859,64606759.0,47.804
"Congo, Rep.",3800610.0,Africa,2125.621418,2315.056572,2464.783157,2677.939642,3213.152683,3259.178978,4879.507522,4201.194937,4016.239529,3484.164376,3484.061970,3632.557798,3800610.0,57.470
Cote d'Ivoire,18013409.0,Africa,1388.594732,1500.895925,1728.869428,2052.050473,2378.201111,2517.736547,2602.710169,2156.956069,1648.073791,1786.265407,1648.800823,1544.750112,18013409.0,54.655
Djibouti,496374.0,Africa,2669.529475,2864.969076,3020.989263,3020.050513,3694.212352,3081.761022,2879.468067,2880.102568,2377.156192,1895.016984,1908.260867,2082.481567,496374.0,54.791
Egypt,80264543.0,Africa,1418.822445,1458.915272,1693.335853,1814.880728,2024.008147,2785.493582,3503.729636,3885.460710,3794.755195,4173.181797,4754.604414,5581.180998,80264543.0,71.338
Equatorial Guinea,551201.0,Africa,375.643123,426.096408,582.841971,915.596003,672.412257,958.566812,927.825343,966.896815,1132.055034,2814.480755,7703.495900,12154.089750,551201.0,51.579
Eritrea,4906585.0,Africa,328.940557,344.161886,380.995843,468.794970,514.324208,505.753808,524.875849,521.134133,582.858510,913.470790,765.350001,641.369524,4906585.0,58.040
Ethiopia,76511887.0,Africa,362.146280,378.904163,419.456416,516.118644,566.243944,556.808383,577.860747,573.741314,421.353465,515.889401,530.053532,690.805576,76511887.0,52.947
Gabon,1454867.0,Africa,4293.476475,4976.198099,6631.459222,8358.761987,11401.948410,21745.573280,15113.361940,11864.408440,13522.157520,14722.841880,12521.713920,13206.484520,1454867.0,61.366
Gambia,1688359.0,Africa,485.230659,520.926711,599.650276,734.782912,756.086836,884.755251,835.809611,611.658861,665.624413,653.730170,660.585600,752.749726,1688359.0,59.448
Ghana,22873338.0,Africa,911.298937,1043.561537,1190.041118,1125.697160,1178.223708,993.223957,876.032569,847.006113,925.060154,1005.245812,1111.984578,1327.608910,22873338.0,60.022
Guinea,9947814.0,Africa,510.196492,576.267025,686.373674,708.759541,741.666231,874.685864,857.250358,805.572472,794.348438,869.449767,945.583584,942.654211,9947814.0,56.007
Guinea-Bissau,1472041.0,Africa,299.850319,431.790457,522.034373,715.580640,820.224588,764.725963,838.123967,736.415392,745.539871,796.664468,575.704718,579.231743,1472041.0,46.388
Kenya,35610177.0,Africa,853.540919,944.438315,896.966373,1056.736457,1222.359968,1267.613204,1348.225791,1361.936856,1341.921721,1360.485021,1287.514732,1463.249282,35610177.0,59.339
Lesotho,2046772.0,Africa,298.846212,335.997115,411.800627,498.639026,496.581592,745.369541,797.263107,773.993214,977.486272,1186.147994,1275.184575,1569.331442,2046772.0,59.685
Liberia,3193942.0,Africa,575.572996,620.969990,634.195163,713.603648,803.005454,640.322438,572.199569,506.113857,636.622919,609.173951,531.482368,414.507341,3193942.0,46.027
Libya,6036914.0,Africa,2387.548060,3448.284395,6757.030816,18772.751690,21011.497210,21951.211760,17364.275380,11770.589800,9640.138501,9467.446056,9534.677467,12057.499280,6036914.0,73.952
Madagascar,19167654.0,Africa,1443.011715,1589.202750,1643.387110,1634.047282,1748.562982,1544.228586,1302.878658,1155.441948,1040.676190,986.295896,894.637082,1044.770126,19167654.0,59.443
Malawi,13327079.0,Africa,369.165080,416.369806,427.901086,495.514781,584.621971,663.223677,632.803921,635.517363,563.200014,692.275810,665.423119,759.349910,13327079.0,49.420
Mali,12031795.0,Africa,452.336981,490.382187,496.174343,545.009887,581.368876,686.395269,618.014064,684.171558,739.014375,790.257985,951.409752,1042.581557,12031795.0,54.467
Mauritania,3270065.0,Africa,743.115910,846.120261,1055.896036,1421.145193,1586.851781,1497.492223,1481.150189,1421.603576,1361.369784,1483.136136,1579.019543,1803.151496,3270065.0,64.164
Mauritius,1250882.0,Africa,1967.955707,2034.037981,2529.067487,2475.387562,2575.484158,3710.982963,3688.037739,4783.586903,6058.253846,7425.705295,9021.815894,10956.991120,1250882.0,72.801
Morocco,33757175.0,Africa,1688.203570,1642.002314,1566.353493,1711.044770,1930.194975,2370.619976,2702.620356,2755.046991,2948.047252,2982.101858,3258.495584,3820.175230,33757175.0,71.164
Mozambique,19951656.0,Africa,468.526038,495.586833,556.686354,566.669154,724.917804,502.319733,462.211415,389.876185,410.896824,472.346077,633.617947,823.685621,19951656.0,46.344
Namibia,2055080.0,Africa,2423.780443,2621.448058,3173.215595,3793.694753,3746.080948,3876.485958,4191.100511,3693.731337,3804.537999,3899.524260,4072.324751,4811.060429,2055080.0,61.999
Niger,12894865.0,Africa,761.879376,835.523403,997.766113,1054.384891,954.209236,808.897073,909.722135,668.300023,581.182725,580.305209,601.074501,619.676892,12894865.0,56.867
Nigeria,135031164.0,Africa,1077.281856,1100.592563,1150.927478,1014.514104,1698.388838,1981.951806,1576.973750,1385.029563,1619.848217,1624.941275,1615.286395,2013.977305,135031164.0,47.472
Reunion,798094.0,Africa,2718.885295,2769.451844,3173.723340,4021.175739,5047.658563,4319.804067,5267.219353,5303.377488,6101.255823,6071.941411,6316.165200,7670.122558,798094.0,76.442
Rwanda,8860588.0,Africa,493.323875,540.289398,597.473073,510.963714,590.580664,670.080601,881.570647,847.991217,737.068595,589.944505,785.653765,863.088464,8860588.0,46.242
Sao Tome and Principe,199579.0,Africa,879.583586,860.736903,1071.551119,1384.840593,1532.985254,1737.561657,1890.218117,1516.525457,1428.777814,1339.076036,1353.092390,1598.435089,199579.0,65.528
Senegal,12267493.0,Africa,1450.356983,1567.653006,1654.988723,1612.404632,1597.712056,1561.769116,1518.479984,1441.720720,1367.899369,1392.368347,1519.635262,1712.472136,12267493.0,63.062
Sierra Leone,6144562.0,Africa,879.787736,1004.484437,1116.639877,1206.043465,1353.759762,1348.285159,1465.010784,1294.447788,1068.696278,574.648158,699.489713,862.540756,6144562.0,42.568
Somalia,9118773.0,Africa,1135.749842,1258.147413,1369.488336,1284.733180,1254.576127,1450.992513,1176.807031,1093.244963,926.960296,930.596428,882.081822,926.141068,9118773.0,48.159
South Africa,44433622.0,Africa,4725.295531,5487.104219,5768.729717,7114.477971,7765.962636,8028.651439,8568.266228,7825.823398,7225.069258,7479.188244,7710.946444,9269.657808,44433622.0,61.888
Sudan,42292929.0,Africa,1615.991129,1770.337074,1959.593767,1687.997641,1659.652775,2202.988423,1895.544073,1507.819159,1492.197043,1632.210764,1993.398314,2602.394995,42292929.0,58.556
Swaziland,1133066.0,Africa,1148.376626,1244.708364,1856.182125,2613.101665,3364.836625,3781.410618,3895.384018,3984.839812,3553.022400,3876.768460,4128.116943,4513.480643,1133066.0,58.474
Tanzania,38139640.0,Africa,716.650072,698.535607,722.003807,848.218657,915.985059,962.492293,874.242607,831.822079,825.682454,789.186223,899.074211,1107.482182,38139640.0,52.517
Togo,5701579.0,Africa,859.808657,925.908320,1067.534810,1477.596760,1649.660188,1532.776998,1344.577953,1202.201361,1034.298904,982.286924,886.220577,882.969944,5701579.0,58.420
Tunisia,10276158.0,Africa,1468.475631,1395.232468,1660.303210,1932.360167,2753.285994,3120.876811,3560.233174,3810.419296,4332.720164,4876.798614,5722.895655,7092.923025,10276158.0,73.923
Uganda,29170398.0,Africa,734.753484,774.371069,767.271740,908.918522,950.735869,843.733137,682.266227,617.724406,644.170797,816.559081,927.721002,1056.380121,29170398.0,51.542
Zambia,11746035.0,Africa,1147.388831,1311.956766,1452.725766,1777.077318,1773.498265,1588.688299,1408.678565,1213.315116,1210.884633,1071.353818,1071.613938,1271.211593,11746035.0,51.821
Zimbabwe,12311143.0,Africa,406.884115,518.764268,527.272182,569.795071,799.362176,685.587682,788.855041,706.157306,693.420786,792.449960,672.038623,469.709298,12311143.0,62.351

## Inspecting Data
We've already see how we can get information about a dataframe using the `.info()` and `.describe()` functions, but there are many ways to get information and view a data frame

* Can also use describe() on data frame selections (like a single column)

In [9]:
# Use the .describe() function on the "gdpPercap" column
df_africa ["gdpPercap_1952"].describe()

count      52.000000
mean     1252.572466
std       982.952116
min       298.846212
25%       534.990554
50%       987.025569
75%      1454.886645
max      4725.295531
Name: gdpPercap_1952, dtype: float64

* We can print the first or last x number of rows of our data frame using the head() and tails() functions.

In [ ]:
# heads() function

In [ ]:
# tails() function

* **Note:** head() and tail() default to 5 rows worth of data. We can also pass a value to either to get more or less rows.
  * E.g.  
  head(10)
  
 ---
  
* Use `.dtypes` method to get the data type for each column

In [10]:
# Write your code here
df_africa.dtypes

pop               float64
continent          object
gdpPercap_1952    float64
gdpPercap_1957    float64
gdpPercap_1962    float64
gdpPercap_1967    float64
gdpPercap_1972    float64
gdpPercap_1977    float64
gdpPercap_1982    float64
gdpPercap_1987    float64
gdpPercap_1992    float64
gdpPercap_1997    float64
gdpPercap_2002    float64
gdpPercap_2007    float64
pop2007           float64
lifeExp2007       float64
dtype: object

* Use `shape` method to get the row and column numbers

In [11]:
# Write your code here
df_africa.shape

(52, 16)

Here we can see the that the data have 52 rows of data and 18 attributes worth of information.

* Use the `len()` function to get numbers of each individually

In [ ]:
# print number of rows of data

In [ ]:
# print number of columns of data

* As seen before we can pass the data frame a column name to get all values for that column


* Print out only the lifeExp2007 column from the data frame

In [13]:
# Write your code here
df_africa ["gdpPercap_1952"]

country
Algeria                     2449.008185
Angola                      3520.610273
Benin                       1062.752200
Botswana                     851.241141
Burkina Faso                 543.255241
Burundi                      339.296459
Cameroon                    1172.667655
Central African Republic    1071.310713
Chad                        1178.665927
Comoros                     1102.990936
Congo, Dem. Rep.             780.542326
Congo, Rep.                 2125.621418
Cote d'Ivoire               1388.594732
Djibouti                    2669.529475
Egypt                       1418.822445
Equatorial Guinea            375.643123
Eritrea                      328.940557
Ethiopia                     362.146280
Gabon                       4293.476475
Gambia                       485.230659
Ghana                        911.298937
Guinea                       510.196492
Guinea-Bissau                299.850319
Kenya                        853.540919
Lesotho                      298.846212
Liberia                      575.572996
Libya                       2387.548060
Madagascar                  1443.011715
Malawi                       369.165080
Mali                         452.336981
Mauritania                   743.115910
Mauritius                   1967.955707
Morocco                     1688.203570
Mozambique                   468.526038
Namibia                     2423.780443
Niger                        761.879376
Nigeria                     1077.281856
Reunion                     2718.885295
Rwanda                       493.323875
Sao Tome and Principe        879.583586
Senegal                     1450.356983
Sierra Leone                 879.787736
Somalia                     1135.749842
South Africa                4725.295531
Sudan                       1615.991129
Swaziland                   1148.376626
Tanzania                     716.650072
Togo                         859.808657
Tunisia                     1468.475631
Uganda                       734.753484
Zambia                      1147.388831
Zimbabwe                     406.884115
Name: gdpPercap_1952, dtype: float64

---
## EXERCISE:
1. How many different country names are there in the gapminder_all.csv file?

---

In [16]:
# Write your code here
df = pd.read_csv ("../data/gapminder_All.csv" , index_col="country")
df.shape

(142, 16)

---
## EXERCISE:
1. What is the last country listed in the Africa data frame?

---

In [22]:
# Write your code here
df_all = pd.read_csv ("../data/gapminder_All.csv" , index_col="country")
df_all.shape

(142, 16)

---
## Get information about a particular column

* Operations like mean, max, min, can be used on individual columns
  * E.g. `df['year'].min()`

In [ ]:
# What is the minimum value in the year column?

---
## EXERCISE:
1. What is the mean life expectancy in 2007 for all countries in all years

1. What is the max population in 2007 for all countries in all years

1. What is the standard deviation for GDP per capita for all countries in all years

In [ ]:
df = pd.read_csv("./data/gapminder_all.csv")
# Mean Life Expectancy in 2007

# Max Population in 2007

# Standard Deviation of GDP per capita in 1952

## Rearange Columns

* This is difficult to do using a csv library or by hand
* The reverse() function will reverse the ordering of a list
     * E.g.   `['a', 'b', 'c']` to `['c', 'b', 'a']`

In [ ]:
# Use the python list() function to get the data frame columns a s list
cols = list(df.columns)
print( cols )

# use the .reverse() function to reverse the ordering of the columns

print ( cols )

* Using that now reversed list above, we can pass the list to the new data frame to reorder the columns

In [ ]:
# Pass the cols variable to the data frame to re-arrange the columns

## Transposing tables

In many cases we may need to transpose the column and rows in a table.  Pandas allows us to to this easily with the `T` command.

In [ ]:
# Print first three rows of the data frame

# Transpose the dataframe and print the first three rows

---
## EXERCISE:
1. Read in a new data frame for the gapminder_Americas.csv file
2. Print the last last three columns of the data frame

---
## Selecting values

Data Frames provides a index as a way to identify the rows of the table. A row also has a position inside the table as well as a label, which uniquely identifies its entry in the DataFrame.

To access a value at the position [ i , j ] (row, column) of a Data Frame, we have two options, depending on what is the meaning of i in use.

### Use DataFrame.iloc[..., ...] to select values by their position
* Allows you to specify location by numerical index similar to 2D version of character selection in strings.

In [ ]:
print("\nData value in first row at first column: ", df.iloc[0, 0])

In [ ]:
print("\nData value in fifth row at third column: ", df.iloc[4, 2])

### Use `DataFrame.loc[..., ...]` to select values by their (index) label.

*   Can specify location by name or by numerical index.

In [ ]:
# Print the value of Albanias GDP per capita in 1952 using .loc

In [ ]:
# Print the value of Bulgarias GDP per capita in 1962 using .loc

---
## EXERCISE
~~~
import pandas
df = pandas.read_csv('data/gapminder_Europe.csv', index_col='country')
~~~

1. Find the Per Capita GDP for Serbia in 2007.
1. Find the Per Capita GDPs for Germany in 1982

In [ ]:
# Write your code here

---
## Slicing Data Frames

### Use `:` on its own to mean all columns or all rows.

*   Just like Python's usual slicing notation, we can print all columns or all rows with `.loc` using the `:`

In [ ]:
# Print all of the row values for all years for Egypt

* Would get the same result printing `df.iloc[0]` (without a second index).
* We can also omit the `:` and get all rows.
    * e.g. `df.loc["Albania"]`

In [ ]:
# Print the GDP per capita for all countries in 1952

*   Would get the same result printing `df["gdpPercap_1952"]`
*   Also get the same result printing `df.gdpPercap_1952` (since it's a column name)

---
## EXERCISE:
1. Print out GDP per capita for all countries in asia in 1972

In [ ]:
# Write your code here

---
### We can also use the `:` to select whole sections of a table 
* Similar to the way we would select a section of from a normal python list, we can do the same with data frames.

In [ ]:
# Print a selection of all countries in the table from Italy to Poland from years 1962 to 1972

Note that in Pandas **slicing using indexes is inclusive at both ends**, which differs from typical python behavior where slicing indicates everything up to but not including the final index.

### Select multiple columns or rows using `DataFrame.iloc` and a named slice.
* We can also make selection from a data frame using the index location of the row or column
    * Remember that in programming languages, we start counting at 0

In [ ]:
#Print the first row of the data frame using the .head() function
print("First row of data frame:\n",  )

# Use iloc to print the value in the first row of the first column
print("\n\nValue in the first row of the first column:\n",  )

# Use iloc to print the values of the first two columns in the first row
print("Values in the first two columes in the first row:\n",  )

* **Note that unlike slicing using column or row names, slicing using indexes is not inclusive**

---
## EXERCISE:
1. Print out all values from Hungary through Montenegro (Europe data) for the years 1977 through 1997

In [ ]:
# Write code here

---
## EXERCISE:
1.  Do the two statements below produce the same output?
    ~~~
    print(df.iloc[0:2, 0:2])
    print(df.loc['Albania':'Belgium', 'gdpPercap_1952':'gdpPercap_1962'])
    ~~~

1.  Based on this,what rule governs what is included (or not) in numerical slices and named slices in Pandas?

---
### Slicing individual rows and columns
* Instead of creating slices of *this* to *that* using the `:`, we can also slice using individual rows and columns by placing names or indexes in brackets `[]`.

In [ ]:
# Print out the GDP per capita of only Italy, Austria, and the United Kingdom in the years 2007 and 1957

---
## EXERCISE:
1. Using the index locations, `print` out the first, third, and eight columns for the sixteenth through nineteenth rows.

---
## Result of slicing can be used in further operations.

In [ ]:
# Print out the max value (.max()) of ALL countries from Italy to Poland for 1962 to 1972

In [ ]:
# Print out the min value (.min()) of ALL countries from Italy to Poland for 1962 to 1972

*   Usually don't just print a slice.
*   All the statistical operators that work on entire data frames work the same way on slices.

## Create data frame from selections

* We can create new data frame by selecting data frames based on values and assigining it to a variable

In [ ]:
# Create a selection of ALL countries from Italy to Poland for 1962 to 1972 and 
#  assign the selection to a variable name "subset_df"

print('Subset of data:\n', subset_df)

## Create DataFrame using query
* We can query values in a data frame to create new selections
* By passing a dataframe query to itself, we can create a new dataframe with only those values

In [ ]:
# Create a query for the "gdpPerCap_1962" series in out subset_df data frame for all values greater than 10000

# Create a new data frame called subset_10k_df by passing that query to the subset_df data frame


print(query_10k)
print(subset_10k_df)
print(subset_10k_df.shape)

---
## EXERCISE:

* Create three data frames and get the size of each one.
    1. Countries with a gdp per capita in 1952 above 10000
    1. Countries with a gdp per capita in 1962 above 10000
    1. Countries with a gdp per capita in 1972 above 10000

---

## Filter a DataFrame using a Boolean mask

* A frame full of Booleans is sometimes called a *mask* because of how it can be used
* Comparison is applied element by element
* Returns a similarly-shaped data frame of `True` and `False`

In [ ]:
# Create a full data frame mask for subset_df with a query for all values in all years greater than 10000
mask_10k = 

print( mask_10k )

* We can use masks to filter an entire dataframe with a single query
    * More efficient than using a single query on multiple columns

In [ ]:
# Pass the mask query to subset_df to create a new data frame mask_subset
mask_subset = 

print(mask_subset)
print("Shape: ", mask_subset.shape)

*   Returns the value where the mask is true, and NaN (Not a Number) where it is false.
*   Useful because NaNs are ignored by operations like max, min, average, etc.


* If we wanted to remove all rows with a NaN value in any column we could use the `.dropna()` function

In [ ]:
# Print the mask_subset data frame with all rows with a single NaN value removed


# Print the shape of the mask_subset data frame with all rows with an NaN values removed

## Create new columns

* We can easily create new columns in the same way we would add a key and value to a dictionary

In [ ]:
# Create a new column in data frame called diff_07_52 that is the difference between gdp per capita from 1952 to 2007


print(df.head(1))

---
## EtherPad

On EtherPad explain what the follow expression does:

    only_Am = df[df['continent'] == 'Americas']

___

## EXERCISE:
1. Explain in simple terms what `idxmin` and `idxmax` do in the short program below.
    ~~~
    df = pd.read_csv('data/gapminder_gdp_europe.csv', index_col='country')
    print(df.idxmin())
    print(df.idymax())
    ~~~

2. When would you use these methods?

---
## PRACTICE EXERCISE.
Using the Gapminder GDP data for Europe, write an expression to select each of the following:
1.  GDP per capita for all countries in 1982.
1.  GDP per capita for Denmark for all years.
1.  GDP per capita for all countries for years *after* 1985.
1.  GDP per capita for each country in 2007 as a multiple of GDP per capita for that country in 1952.
---

# -- COMMIT YOUR WORK TO GITHUB --

---
## Keypoints:
 - "Use `DataFrame.iloc[..., ...]` to select values by index location."
 - "Use `:` on its own to mean all columns or all rows."
 - "Select multiple columns or rows using `DataFrame.ix` and a named slice."
 - "Result of slicing can be used in further operations."
 - "Use comparisons to select data based on value."
 - "Select values or NaN using a Boolean mask."